language: python
python:
  - "3.6"

services:
  - docker

before_scripts: pip install docker-compose

after_success: npm run coverage

script:
  - docker-compose -f test.yml run app_test sh -c "npm run test"