version: "3"

services:
  app_dev:
    build:
      context: .
      dockerfile: ./compose/development/Dockerfile
    volumes:
      - ./:/app
    container_name: app_dev
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    command: >
      sh -c "./wait-for.sh postgres_dev:5432 &&
            npx sequelize-cli db:drop &&
            npx sequelize-cli db:create &&
            npx sequelize-cli db:migrate &&
            npm run dev"
    depends_on:
      - postgres_dev

  postgres_dev:
    image: postgres:10-alpine
    volumes:
      - pg_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=yymqaPGT9h6z2TNezMtX
      - POSTGRES_USER=postgres
      - POSTGRES_DB=movies_dev

volumes:
  pg_dev: {}