version: "3"

services:
  postgres:
    image: postgres:10-alpine
    volumes:
      - pg_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=yymqaPGT9h6z2TNezMtX
      - POSTGRES_USER=postgres
      - POSTGRES_DB=movies_prod

volumes:
  pg_dev: {}