version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    command: >
      sh -c "sleep 2 &&
            npx sequelize db:drop &&
            npx sequelize db:create &&
            npx sequelize db:migrate &&
            npm run test"
    env_file: ./compose/testing/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=yymqaPGT9h6z2TNezMtX
      - POSTGRES_USER=postgres
      - POSTGRES_DB=movies

volumes:
  pg: {}